import type { Inquiry, Property } from "@/types/property";

export const mockProperties: Property[] = [
  {
    id: "prop-1",
    title: "3 BHK Luxury Flat with Garden View",
    description:
      "Newly constructed flat near main market, 24x7 water supply. Beautiful interiors with modular kitchen and premium fittings.",
    listingType: "Sell",
    category: "Flat",
    price: 7500000,
    isNegotiable: true,
    maintenanceCost: 2000,
    city: "Patna",
    locality: "Kankarbagh",
    address: "Road No 5, Near Old Water Tank",
    amenities: ["Gym", "Lift", "Parking", "Wifi", "Power Backup", "Security"],
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
      "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800",
    ],
    details: {
      bhk: 3,
      bathrooms: 2,
      areaSqFt: 1450,
      furnishing: "Semi Furnished",
      floor: 2,
      totalFloors: 5,
      facing: "East",
      parking: true,
      constructionStatus: "Ready to Move",
    },
    owner: {
      id: "user-1",
      firstName: "Rahul",
      lastName: "Kumar",
      phoneNumber: "+91 9876543210",
      email: "rahul@test.com",
      avatarUrl:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
    },
    isAvailable: true,
    isSaved: false,
    viewsCount: 156,
    createdAt: "2026-02-01T10:00:00.000Z",
  },
  {
    id: "prop-2",
    title: "2 BHK Flat for Rent in Prime Location",
    description:
      "Well-maintained flat in gated society. Close to schools, hospitals and shopping centers.",
    listingType: "Rent",
    category: "Flat",
    price: 15000,
    isNegotiable: true,
    maintenanceCost: 1500,
    city: "Patna",
    locality: "Boring Road",
    address: "Near South Gandhi Maidan",
    amenities: ["Lift", "Parking", "Security", "Garden"],
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
      "https://images.unsplash.com/photo-1560185007-5f0bb1866cab?w=800",
    ],
    details: {
      bhk: 2,
      bathrooms: 2,
      areaSqFt: 950,
      furnishing: "Fully Furnished",
      floor: 4,
      totalFloors: 8,
      facing: "North",
      parking: true,
      constructionStatus: "Ready to Move",
    },
    owner: {
      id: "user-2",
      firstName: "Priya",
      lastName: "Singh",
      phoneNumber: "+91 8765432109",
      email: "priya@test.com",
      avatarUrl:
        "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
    },
    isAvailable: true,
    isSaved: true,
    viewsCount: 89,
    createdAt: "2026-02-03T14:30:00.000Z",
  },
  {
    id: "prop-3",
    title: "Independent House with Modern Amenities",
    description:
      "Spacious independent house with lawn and parking. Perfect for families.",
    listingType: "Sell",
    category: "House",
    price: 12500000,
    isNegotiable: false,
    city: "Patna",
    locality: "Rajendra Nagar",
    address: "Lane 4, Near Central Park",
    amenities: ["Garden", "Parking", "Power Backup", "Water Supply"],
    images: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
    ],
    details: {
      bhk: 4,
      bathrooms: 3,
      areaSqFt: 2200,
      furnishing: "Unfurnished",
      totalFloors: 2,
      facing: "South",
      parking: true,
      constructionStatus: "Ready to Move",
    },
    owner: {
      id: "user-3",
      firstName: "Amit",
      lastName: "Verma",
      phoneNumber: "+91 7654321098",
      email: "amit@test.com",
    },
    isAvailable: true,
    isSaved: false,
    viewsCount: 234,
    createdAt: "2026-01-28T09:15:00.000Z",
  },
  {
    id: "prop-4",
    title: "Commercial Shop in Busy Market",
    description:
      "Prime location shop with high footfall. Ideal for retail business.",
    listingType: "Rent",
    category: "Commercial",
    price: 35000,
    isNegotiable: true,
    city: "Patna",
    locality: "Maurya Lok",
    address: "Ground Floor, Complex A",
    amenities: ["Power Backup", "Security", "Parking"],
    images: [
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
    ],
    details: {
      areaSqFt: 450,
      constructionStatus: "Ready to Move",
    },
    owner: {
      id: "user-4",
      firstName: "Sunita",
      lastName: "Devi",
      phoneNumber: "+91 6543210987",
      email: "sunita@test.com",
    },
    isAvailable: true,
    isSaved: false,
    viewsCount: 67,
    createdAt: "2026-02-05T16:45:00.000Z",
  },
  {
    id: "prop-5",
    title: "Residential Plot in Developing Area",
    description:
      "East facing plot in upcoming residential area. Good investment opportunity.",
    listingType: "Sell",
    category: "Plot",
    price: 4500000,
    isNegotiable: true,
    city: "Patna",
    locality: "Danapur",
    address: "Near NH-30",
    amenities: ["Road Access", "Water Supply", "Electricity"],
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800",
    ],
    details: {
      areaSqFt: 2400,
      facing: "East",
    },
    owner: {
      id: "user-5",
      firstName: "Rajan",
      lastName: "Mishra",
      phoneNumber: "+91 5432109876",
      email: "rajan@test.com",
    },
    isAvailable: true,
    isSaved: false,
    viewsCount: 112,
    createdAt: "2026-02-04T11:20:00.000Z",
  },
  {
    id: "prop-6",
    title: "PG Accommodation for Working Professionals",
    description: "Fully furnished PG with meals included. AC rooms available.",
    listingType: "PG",
    category: "Flat",
    price: 8000,
    isNegotiable: false,
    maintenanceCost: 0,
    city: "Patna",
    locality: "Bailey Road",
    address: "Near IGIMS Hospital",
    amenities: ["Wifi", "Meals", "AC", "Laundry", "Security"],
    images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800"],
    details: {
      bhk: 1,
      bathrooms: 1,
      areaSqFt: 180,
      furnishing: "Fully Furnished",
    },
    owner: {
      id: "user-6",
      firstName: "Neha",
      lastName: "Sharma",
      phoneNumber: "+91 4321098765",
      email: "neha@test.com",
    },
    isAvailable: true,
    isSaved: true,
    viewsCount: 45,
    createdAt: "2026-02-06T08:00:00.000Z",
  },
];

export const mockInquiries: Inquiry[] = [
  {
    id: "inq-1",
    message: "Is the price negotiable? I am interested in visiting.",
    createdAt: "2026-02-06T14:30:00.000Z",
    property: {
      id: "prop-1",
      title: "3 BHK Luxury Flat with Garden View",
    },
    buyer: {
      firstName: "Suresh",
      phoneNumber: "+91 9998887776",
      email: "suresh@test.com",
    },
  },
  {
    id: "inq-2",
    message: "Can I schedule a visit this weekend?",
    createdAt: "2026-02-05T10:15:00.000Z",
    property: {
      id: "prop-1",
      title: "3 BHK Luxury Flat with Garden View",
    },
    buyer: {
      firstName: "Meena",
      phoneNumber: "+91 8887776665",
      email: "meena@test.com",
    },
  },
  {
    id: "inq-3",
    message: "Is parking included in the rent?",
    createdAt: "2026-02-04T18:45:00.000Z",
    property: {
      id: "prop-2",
      title: "2 BHK Flat for Rent in Prime Location",
    },
    buyer: {
      firstName: "Vikram",
      phoneNumber: "+91 7776665554",
      email: "vikram@test.com",
    },
  },
];

export const cities = [
  "Patna",
  "Delhi",
  "Mumbai",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
];

export const amenitiesList = [
  "Gym",
  "Lift",
  "Parking",
  "Wifi",
  "Power Backup",
  "Security",
  "Garden",
  "Swimming Pool",
  "Clubhouse",
  "AC",
  "Meals",
  "Laundry",
  "Water Supply",
  "Road Access",
  "Electricity",
];
