import {
  Scale,
  Code,
  Palette,
  Megaphone,
  Camera,
  Share2,
  Search,
  Users,
  ShoppingCart,
  Building2,
  MessageSquare,
  Phone,
  MoreHorizontal,
  type LucideIcon,
} from "lucide-react";

export interface Service {
  name: string;
  id: string;
}

export interface ServiceCategory {
  id: string;
  title: string;
  description: string;
  icon: LucideIcon;
  services: Service[];
}

export const serviceCategories: ServiceCategory[] = [
  {
    id: "legal",
    title: "Legal Support Services",
    description: "Complete compliance and certification solutions",
    icon: Scale,
    services: [
      { id: "bis", name: "BIS Certification" },
      { id: "isi", name: "ISI Certification" },
      { id: "hallmark", name: "Hall Mark" },
      { id: "esic", name: "ESIC/PF" },
      { id: "labour", name: "Labour License" },
      { id: "fssai", name: "FSSAI Registration/License" },
      { id: "trademark", name: "Trademark Registration" },
      { id: "factory", name: "Factory License" },
      { id: "iso", name: "ISO Certification" },
      { id: "pollution", name: "Pollution License" },
      { id: "iec", name: "Import Export Code" },
      { id: "ngo", name: "NGO/Society/Trust" },
      { id: "gmp", name: "GMP Certification" },
      { id: "cf", name: "CF Certification" },
      { id: "drug", name: "Drug License" },
      { id: "gem", name: "GEM Registration" },
      { id: "msme", name: "MSME" },
      { id: "nsic", name: "NSIC Registration" },
      { id: "partnership", name: "Partnership Deed Registration" },
      { id: "rera", name: "RERA" },
      { id: "copyright", name: "Copyright/Patent" },
      { id: "fire", name: "Fire & Safe" },
      { id: "nabl", name: "NABL Certification" },
      { id: "dsc", name: "DSC (Digital Signature Certificate)" },
      { id: "calibration", name: "Calibration" },
      { id: "stability", name: "Stability Testing" },
      { id: "peso", name: "PESO Certification" },
      { id: "inspection", name: "Third Party Inspection" },
      { id: "welding", name: "Welding Inspection" },
      { id: "shop", name: "Shop Establishment Registration" },
      { id: "dipp", name: "DIPP Registration" },
      { id: "firenoc", name: "Fire & Safety NOC" },
      { id: "weight", name: "Weight & Measurement" },
      { id: "employee", name: "Employee Management" },
      { id: "startup", name: "Startup India" },
      { id: "newbusiness", name: "New Business Startup Assistance" },
      {
        id: "company",
        name: "Company Incorporation (Pvt Ltd, Public Ltd, OPC, Nidhi)",
      },
      { id: "psara", name: "PSARA Registration" },
      { id: "ucan", name: "UCAN Certificate" },
      { id: "haccp", name: "HACCP Certification" },
      { id: "accounting", name: "Accounting" },
      { id: "12a80g", name: "12A/80G" },
      { id: "llp", name: "LLP Registration" },
      { id: "project", name: "Project Report & CMA Data" },
      { id: "gst", name: "GST Registration" },
      { id: "itr", name: "ITR Filing" },
    ],
  },
  {
    id: "development",
    title: "Development",
    description: "Web & mobile solutions for your business",
    icon: Code,
    services: [
      { id: "website", name: "Website Designing & Development" },
      { id: "mobile", name: "Mobile App Designing & Development" },
      { id: "crm", name: "CRM Development" },
      { id: "lead", name: "Customer Lead Management" },
    ],
  },
  {
    id: "graphic",
    title: "Graphic Designing",
    description: "Creative visual solutions for branding",
    icon: Palette,
    services: [
      { id: "logo", name: "Logo Design" },
      { id: "businesscard", name: "Business Card" },
      { id: "letterhead", name: "Letterhead" },
      { id: "poster", name: "Poster" },
      { id: "banner", name: "Banner" },
      { id: "envelope", name: "Envelope" },
      { id: "brochure", name: "Brochure" },
      { id: "socialmedia", name: "Social Media Post" },
      { id: "flyer", name: "Flyer" },
      { id: "gifttag", name: "Gift Tag" },
      { id: "bookcover", name: "Book Cover" },
      { id: "standee", name: "Standee" },
      { id: "tshirt", name: "T-shirt Design" },
      { id: "invitation", name: "Invitation Card Design" },
      { id: "packaging", name: "Packing Design" },
      { id: "calendar", name: "Calendar And Diary Design" },
      { id: "menu", name: "Menu Card Design" },
      { id: "signboard", name: "Signboard Design" },
      { id: "bill", name: "Bill Design" },
      { id: "icard", name: "I-card Design" },
    ],
  },
  {
    id: "branding",
    title: "Company Branding",
    description: "Build your brand identity",
    icon: Megaphone,
    services: [
      { id: "graphicwork", name: "All Types of Graphic Work" },
      { id: "promotion", name: "Promotion Propaganda Set" },
      { id: "jingle", name: "Jingle Design and Recording" },
      { id: "caption", name: "Caption Writing" },
      { id: "competitor", name: "Competitor Analysis" },
    ],
  },
  {
    id: "photovideo",
    title: "Photo & Video Shoot",
    description: "Professional media production",
    icon: Camera,
    services: [
      { id: "productphoto", name: "Product Photoshoot" },
      { id: "modelphoto", name: "Model Photoshoot" },
      { id: "videoads", name: "Video Ads Making" },
      { id: "shortfilm", name: "Short Film Making" },
    ],
  },
  {
    id: "socialmedia",
    title: "Social Media & Search Engine Promotion",
    description: "Reach your target audience",
    icon: Share2,
    services: [
      { id: "facebook", name: "Facebook Ads" },
      { id: "instagram", name: "Instagram Ads" },
      { id: "x", name: "X Ads" },
      { id: "linkedin", name: "LinkedIn Ads" },
      { id: "google", name: "Google Ads" },
      { id: "youtube", name: "YouTube Ads" },
      { id: "ott", name: "OTT Ads" },
      { id: "call", name: "Call Ads" },
      { id: "sms", name: "SMS Ads" },
      { id: "whatsapp", name: "WhatsApp Ads" },
      { id: "ang", name: "Ang Ads" },
    ],
  },
  {
    id: "seo",
    title: "Search Engine Optimization",
    description: "Improve your online visibility",
    icon: Search,
    services: [
      { id: "websiteseo", name: "Website SEO (On-page, Off-page & Technical)" },
      { id: "gmb", name: "Google My Business SEO" },
      { id: "youtubeseo", name: "YouTube SEO" },
      { id: "content", name: "Content Writing" },
    ],
  },
  {
    id: "creator",
    title: "Content Creator Support",
    description: "Support for influencers & creators",
    icon: Users,
    services: [
      { id: "videoshoot", name: "Video Shoot" },
      { id: "videoediting", name: "Video Editing" },
      { id: "trendresearch", name: "Current Market Trend Research" },
      { id: "profilemaintain", name: "Social Media Profile Maintain" },
      { id: "thumbnail", name: "Thumbnail Design" },
      { id: "fanrelation", name: "Social Media Fans Relationship Maintain" },
    ],
  },
  {
    id: "ecommerce",
    title: "Complete E-Commerce Service",
    description: "End-to-end online selling solutions",
    icon: ShoppingCart,
    services: [
      { id: "eproductphoto", name: "Product Photoshoot" },
      { id: "evideoads", name: "Video Ads Recording" },
      { id: "ejingle", name: "Jingle Recording" },
      { id: "ewebsite", name: "Website Design and Development" },
      { id: "emobile", name: "Mobile App Design and Development" },
      { id: "payment", name: "Payment Gateway Registration" },
      { id: "delivery", name: "Delivery Partner Registration" },
      { id: "aggregator", name: "E-commerce Aggregator Platform Registration" },
      { id: "listing", name: "Product Listing" },
      { id: "esocialmedia", name: "Social Media Post" },
      { id: "esocialads", name: "Social Media Ads" },
      { id: "egoogleads", name: "Google Ads" },
      { id: "eproductmgmt", name: "E-Commerce Platform Product Management" },
      { id: "ewebsiteseo", name: "Website SEO" },
      { id: "customercare", name: "Customer Care Service" },
    ],
  },
  {
    id: "3d",
    title: "3D Building Elevation / Naksha",
    description: "Architectural visualization services",
    icon: Building2,
    services: [
      { id: "outside3d", name: "Flat, Shopping Mall Outside 3D Elevation" },
      { id: "interior3d", name: "Inside Interior 3D Elevation" },
      { id: "plansheet", name: "House / Industry Plan Sheets" },
    ],
  },
  {
    id: "whatsappapi",
    title: "WhatsApp Business API Service",
    description: "Automate customer communication",
    icon: MessageSquare,
    services: [
      { id: "bulk", name: "WhatsApp Bulk" },
      { id: "chatflow", name: "WhatsApp E-Commerce Chat Flow" },
      { id: "store", name: "WhatsApp E-Commerce Store Making" },
      { id: "flow", name: "WhatsApp Chat Flow" },
    ],
  },
  {
    id: "ivr",
    title: "IVR Service",
    description: "Professional telephony solutions",
    icon: Phone,
    services: [
      { id: "teleads", name: "Tele Ads" },
      { id: "tollfree", name: "Toll Free Number" },
      { id: "officeivr", name: "Office IVR" },
    ],
  },
  {
    id: "others",
    title: "Other Services",
    description: "Additional business support",
    icon: MoreHorizontal,
    services: [
      { id: "telecalling", name: "Tele Calling" },
      { id: "channelmaint", name: "Ang Growth Channel Maintenance" },
      { id: "ovideoads", name: "Video Ads" },
      { id: "audioads", name: "Audio Ads" },
      { id: "music", name: "Music Recording" },
      { id: "printing", name: "Printing Service" },
      { id: "courier", name: "Courier Services" },
    ],
  },
];
